// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DatesCardModuleCssNamespace {
    export interface IDatesCardModuleCss {
        end: string;
        main: string;
        start: string;
    }
}

declare const DatesCardModuleCssModule: DatesCardModuleCssNamespace.IDatesCardModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DatesCardModuleCssNamespace.IDatesCardModuleCss;
};

export = DatesCardModuleCssModule;
