// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleCssNamespace {
    export interface IIndexModuleCss {
        container: string;
        form: string;
        gsheetCard: string;
        'input-med': string;
        'input-sm': string;
        invisible: string;
        menuButtons: string;
        'react-table-lite-container': string;
        visible: string;
    }
}

declare const IndexModuleCssModule: IndexModuleCssNamespace.IIndexModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleCssNamespace.IIndexModuleCss;
};

export = IndexModuleCssModule;
