// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace InfoCardModuleCssNamespace {
    export interface IInfoCardModuleCss {
        additional: string;
        address: string;
        contact: string;
        container: string;
        'info-capitalised': string;
        'info-lowercase': string;
        'info-uppercase': string;
        main: string;
        people: string;
        renter: string;
    }
}

declare const InfoCardModuleCssModule: InfoCardModuleCssNamespace.IInfoCardModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: InfoCardModuleCssNamespace.IInfoCardModuleCss;
};

export = InfoCardModuleCssModule;
