// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace OptionsCardModuleScssNamespace {
    export interface IOptionsCardModuleScss {
        cleaning: string;
        fees: string;
        invisible: string;
        labelFees: string;
        main: string;
        sheets: string;
        visible: string;
    }
}

declare const OptionsCardModuleScssModule: OptionsCardModuleScssNamespace.IOptionsCardModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: OptionsCardModuleScssNamespace.IOptionsCardModuleScss;
};

export = OptionsCardModuleScssModule;
