// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PricesCardModuleCssNamespace {
    export interface IPricesCardModuleCss {
        arrhes: string;
        garantie: string;
        invisible: string;
        main: string;
        price: string;
        prices: string;
        visible: string;
    }
}

declare const PricesCardModuleCssModule: PricesCardModuleCssNamespace.IPricesCardModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PricesCardModuleCssNamespace.IPricesCardModuleCss;
};

export = PricesCardModuleCssModule;
